services:
  verde_clinic:
    build: .
    container_name: verde_clinic_app
    ports:
      - "5007:5007"
    env_file:
      - .env
    volumes:
      - ./verde_clinic.db:/app/verde_clinic.db
      - ./backups:/app/backups
      - ./exports:/app/exports
    restart: unless-stopped
