services:
  la_verde_almasala:
    build: .
    container_name: la_verde_almasala_app
    ports:
      - "${PORT:-8090}:5007"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ./exports:/app/exports
    restart: unless-stopped
